_target_: ${csi}.modules.MultiTaskDistillLossSmooth
dwpose_cfg: ${resources.dwpose_cfg}
dwpose_ckpt: ${resources.dwpose_ckpt}
vitpose_cfg: ${resources.vitpose_cfg}
vitpose_ckpt: ${resources.vitpose_ckpt}
ctc_weight: 1.0
dwpose_weight: 1.0
vitpose_weight: 0.0
dwpose_dist_temperature: 8.0
smooth_weight: 1.0
smooth_tau: 3.0
