_target_: ${csi}.modules.MultiTaskDistillLoss
dwpose_cfg: ${resources.dwpose_cfg}
dwpose_ckpt: ${resources.dwpose_ckpt}
vitpose_cfg: ${resources.vitpose_cfg}
vitpose_ckpt: ${resources.vitpose_ckpt}
ctc_weight: 1.0
dwpose_weight: 0.0
vitpose_weight: 0.0
dwpose_dist_temperature: 0.0
