#@package _global_
defaults:
  - /prefix@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /datamodule: ph14
  - /transforms/train: 224x224
  - /transforms/test: 224x224
  - /model: efficientnet_small_trans
  - /loss: multitask_distill
  - /resources: mec

seed: 3407
epoch: 200
tags:
  - efficient_net
  - transforms

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt
devices: [1]

datamodule:
  batch_size: 2
  num_workers: 6
  train_shuffle: False

optimizer:
  lr: 1e-4

lr_scheduler:
  milestones: [40, 65, 80, 85, 90]
  gamma: 0.1

loss:
  ctc_weight: 1.0
  dwpose_weight: 0.0
  vitpose_weight: 0.
  dwpose_dist_temperature: 0.0
