#@package _global_
defaults:
  - /prefix@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: step
  - /datamodule: ph14
  - /transforms/train: 224x224
  - /transforms/test: 224x224
  - /model: resnet_distill_csplit_efficient
  - /loss: multitask_distill
  - /resources: mec

seed: 3407
epoch: 200
tags:
  - multitask_distill
  - channel_split
  - dwpose
  - resnet
  - sparse_attention

model:
  encoder:
    csplit_simcc_ratio: 0.5
    csplit_heatmap_ratio: 0.0
    n_keypoints_simcc: 133
    n_keypoints_heatmap: 0
    simcc_x_samples: 384
    simcc_y_samples: 512
    enable_heatmap: false
    enable_simcc: True
    drop_prob: 0.0

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt
devices: [1]

datamodule:
  batch_size: 1
  num_workers: 4
  train_shuffle: False

optimizer:
  lr: 1e-4

lr_scheduler:
  step_size: 40
  gamma: 0.1
