#@package _global_
defaults:
  - /prefix@_global_
  - /hydra: no_output
  - /optimizer: adam
  - /lr_scheduler: multistep
  - /datamodule: ph14
  - /transforms/train: 224x224
  - /transforms/test: 224x224
  - /model: resnet_50_trans
  - /loss: multitask_distill_ctc_only
  - /resources: mec

seed: 3407
epoch: 200
tags:
  - baseline
  - resnet50
  - transform

#if continuos read model
load_weights: False
is_resume: False
checkpoint: outputs/train_lightning/2024-04-24_01-42-41/last.ckpt
devices: [0]

datamodule:
  batch_size: 2
  num_workers: 6
  train_shuffle: False

optimizer:
  lr: 1e-4

lr_scheduler:
  milestones: [40, 65, 80, 85, 90]
  gamma: 0.1
