_target_: ${csi}.modules.base_stream.BaseStream
encoder:
  _target_: ${csi}.modules.ResnetEncoder
  cfg: ${resnet_cfg}
  ckpt: ${resnet_ckpt}
  drop_prob: 0.5
neck:
  _target_: ${csi}.modules.TemporalConvNeck
  in_channels: 512
  out_channels: 1024
  bottle_channels: 512
  n_class: 1296
  with_header: True,
  pooling: max
  dropout: 0.2
decoder:
  _target_: ${csi}.modules.TransformerDecoder
  n_class: 1296
  d_model: 1024
  n_heads: 8
  n_layers: 8
  d_feedforward: 2048
  dropout: 0.2
