_target_: ${csi}.modules.base_stream.BaseStream
encoder:
  _target_: ${csi}.modules.DualTaskStreamEncoder
  visual_backbone:
    _target_: ${csi}.modules.TimmResNetBackbone
    model_name: resnet18
  fusion:
    _target_: ${csi}.modules.FusionA
    num_keypoints: 133
    feats_dim: 512
    hidden_dim: 1024
  pose_ckpt: ${resources.dwpose_ckpt}
  pose_cfg: ${resources.dwpose_cfg}
decoder:
  _target_: ${csi}.modules.EfficientDecoder
  input_dims: 512
  d_model: 1024
  n_layers: 8
  n_head: 8
  n_classes: 1296
  bucket_size: 4
  conv_kernel_head: 5
  conv_kernel_block: 3
  ff_dropout: 0.0
  drop_path: 0.0
